# Generated by Django 5.0.1 on 2024-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_changelog_delete_changehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='change_description',
            field=models.TextField(null=True),
        ),
    ]
