# Generated by Django 5.0.1 on 2024-03-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_remove_changelog_version_number'),
        ('content_management', '0026_alter_changelog_change_description'),
    ]

    operations = [
    ]
