# Generated by Django 5.0.1 on 2024-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0027_merge_20240329_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='change_type',
            field=models.CharField(choices=[('module', 'Module'), ('folder', 'Folder'), ('none', 'None')], default='none'),
        ),
    ]
