# Generated by Django 5.0.1 on 2024-04-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0028_changelog_change_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='change_type',
        ),
    ]
